name: Extract character frequency list

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate a.txt from b.json
        run: |
          jq -r '.words[].entry.form' b.json \
          | fold -w1 \
          | grep -P '[^/]' \
          | sort \
          | uniq -c \
          | sort -nr \
          > a.txt

      - name: Commit and push a.txt
        run: |
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add a.txt
          git pull
          git commit -m "Update character frequency list (auto)"
          git push
